export const roadmapCopy = {
  en: ["Jamd · JAMD: proposed roadmap", "Confirmed identity: fixed supply of 1 billion. Allocation below is a proposal, not an executed distribution or an active sale.", "Community", "Treasury", "Founder and team", "Ecosystem", "Liquidity reserve", "Proposal: lock 90% of community, treasury and ecosystem allocations and 100% of team tokens: 87% of total supply. No release for 24 calendar months, then monthly over 36 months. Liquidity requires additional SOL or USDC; reserving tokens does not fund a market.", "Verified in Devnet: creation, metadata and creator vault. Pending: 20 AI credits / 7-day trial, payments, participant eligibility and effective liquidity locks. Mainnet requires independent audit, legal review and verified administration. No launch date or return is promised.", "Token allocation proposal"],
  es: ["Jamd · JAMD: hoja de ruta propuesta", "Identidad confirmada: suministro fijo de 1.000 millones. La distribución siguiente es una propuesta, no un reparto ejecutado ni una venta activa.", "Comunidad", "Tesorería", "Fundador y equipo", "Ecosistema", "Reserva de liquidez", "Propuesta: bloquear el 90% de comunidad, tesorería y ecosistema y el 100% del equipo: 87% del suministro total. Sin liberaciones durante 24 meses naturales; después, mensualmente durante 36 meses. La liquidez requiere SOL o USDC adicionales; reservar tokens no financia un mercado.", "Verificado en Devnet: creación, metadatos y depósito bloqueado del creador. Pendiente: trial de 20 créditos de IA / 7 días, pagos, elegibilidad de participantes y bloqueo efectivo de liquidez. Mainnet requiere auditoría independiente, revisión legal y administración verificada. Sin fecha de lanzamiento ni rentabilidad prometidas.", "Propuesta de distribución del token"],
  fr: ["Jamd · JAMD : feuille de route proposée", "Identité confirmée : offre fixe d’un milliard. La répartition est une proposition, ni une distribution réalisée ni une vente active.", "Communauté", "Trésorerie", "Fondateur et équipe", "Écosystème", "Réserve de liquidité", "Proposition : bloquer 90 % des parts communauté, trésorerie et écosystème et 100 % de l’équipe, soit 87 % du total. Aucun déblocage pendant 24 mois calendaires, puis mensuellement sur 36 mois. La liquidité nécessite aussi du SOL ou de l’USDC ; réserver des tokens ne finance pas un marché.", "Vérifié sur Devnet : création, métadonnées et coffre du créateur. En attente : essai de 20 crédits IA / 7 jours, paiements, admissibilité et verrouillage effectif de liquidité. Mainnet exige audit indépendant, examen juridique et administration vérifiée. Aucune date ni rentabilité promise.", "Répartition proposée"],
  de: ["Jamd · JAMD: vorgeschlagener Fahrplan", "Bestätigt: feste Menge von einer Milliarde. Die Verteilung ist ein Vorschlag, keine ausgeführte Zuteilung und kein aktiver Verkauf.", "Community", "Projektreserve", "Gründer und Team", "Ökosystem", "Liquiditätsreserve", "Vorschlag: 90 % von Community, Projektreserve und Ökosystem sowie 100 % des Teams sperren: insgesamt 87 %. Keine Freigabe für 24 Kalendermonate, danach monatlich über 36 Monate. Liquidität benötigt zusätzlich SOL oder USDC; reservierte Tokens finanzieren keinen Markt.", "Auf Devnet geprüft: Erstellung, Metadaten und Gründer-Tresor. Offen: 20 KI-Credits / 7 Tage Testzugang, Zahlungen, Teilnahmeberechtigung und tatsächliche Liquiditätssperren. Mainnet erfordert unabhängiges Audit, rechtliche Prüfung und geprüfte Verwaltung. Kein Starttermin oder Ertrag versprochen.", "Vorgeschlagene Token-Verteilung"],
  pt: ["Jamd · JAMD: roteiro proposto", "Identidade confirmada: oferta fixa de mil milhões. A distribuição é uma proposta, não uma atribuição executada nem uma venda ativa.", "Comunidade", "Tesouraria", "Fundador e equipa", "Ecossistema", "Reserva de liquidez", "Proposta: bloquear 90% da comunidade, tesouraria e ecossistema e 100% da equipa: 87% do total. Sem libertação durante 24 meses de calendário, depois mensalmente por 36 meses. Liquidez exige SOL ou USDC adicionais; reservar tokens não financia um mercado.", "Verificado na Devnet: criação, metadados e cofre do criador. Pendente: teste de 20 créditos de IA / 7 dias, pagamentos, elegibilidade e bloqueio efetivo de liquidez. Mainnet exige auditoria independente, revisão jurídica e administração verificada. Sem data ou rentabilidade prometida.", "Distribuição proposta"],
  it: ["Jamd · JAMD: percorso proposto", "Identità confermata: offerta fissa di un miliardo. La distribuzione è una proposta, non un’assegnazione eseguita né una vendita attiva.", "Comunità", "Tesoreria", "Fondatore e team", "Ecosistema", "Riserva di liquidità", "Proposta: bloccare il 90% di comunità, tesoreria ed ecosistema e il 100% del team: 87% del totale. Nessun rilascio per 24 mesi di calendario, poi mensilmente per 36 mesi. La liquidità richiede anche SOL o USDC; riservare token non finanzia un mercato.", "Verificato su Devnet: creazione, metadati e deposito del creatore. Da completare: prova di 20 crediti IA / 7 giorni, pagamenti, idoneità e blocco effettivo della liquidità. Mainnet richiede audit indipendente, revisione legale e amministrazione verificata. Nessuna data o rendimento promesso.", "Distribuzione proposta"],
  ja: ["Jamd · JAMD：ロードマップ案", "確定事項：固定供給量10億枚。以下は配分案であり、実行済みの配分や販売ではありません。", "コミュニティ", "運営準備金", "創設者・チーム", "エコシステム", "流動性準備金", "案：コミュニティ・運営準備金・エコシステムの90%、チームの100%をロック。総供給量の87%です。暦上24か月は解除せず、その後36か月かけて毎月解除します。流動性には別途SOLまたはUSDCが必要で、トークンの確保だけでは市場を賄えません。", "Devnetで確認済み：作成、メタデータ、創設者の保管庫。未完了：AIクレジット20件・7日間の試用、決済、参加資格、実効的な流動性ロック。Mainnetには独立監査、法的審査、管理体制の検証が必要です。開始日や利益は約束しません。", "トークン配分案"],
  ko: ["Jamd · JAMD: 로드맵 제안", "확정 사항: 고정 공급량 10억 개. 아래 배분은 제안이며 실행된 배분이나 진행 중인 판매가 아닙니다.", "커뮤니티", "프로젝트 준비금", "창립자 및 팀", "생태계", "유동성 준비금", "제안: 커뮤니티·준비금·생태계의 90%, 팀의 100%를 잠금: 총공급량의 87%. 달력 기준 24개월 동안 해제하지 않고 이후 36개월간 매월 해제합니다. 유동성에는 별도의 SOL 또는 USDC가 필요하며 토큰 확보만으로 시장 자금이 마련되지 않습니다.", "Devnet 검증 완료: 생성, 메타데이터, 창립자 보관소. 미완료: AI 크레딧 20개 / 7일 체험, 결제, 참여 자격, 실질적 유동성 잠금. Mainnet에는 독립 감사, 법률 검토, 관리 체계 검증이 필요합니다. 출시일이나 수익을 약속하지 않습니다.", "토큰 배분 제안"],
  zh: ["Jamd · JAMD：路线图提案", "已确认：固定供应量10亿枚。以下分配仅为提案，并非已执行的分配或正在进行的销售。", "社区", "项目储备", "创始人及团队", "生态系统", "流动性储备", "提案：锁定社区、项目储备和生态系统份额的90%，团队份额的100%，合计总供应量的87%。24个自然月内不解锁，随后36个月按月释放。流动性还需要额外的SOL或USDC；预留代币并不等于为市场提供资金。", "Devnet已验证：创建、元数据和创始人金库。待完成：20个AI积分／7天试用、支付、参与资格和实际流动性锁定。Mainnet需要独立审计、法律审查和管理机制验证。不承诺上线日期或收益。", "代币分配提案"],
  ar: ["Jamd · JAMD: خارطة طريق مقترحة", "المؤكد: معروض ثابت قدره مليار توكن. التوزيع التالي اقتراح وليس توزيعاً منفذاً أو بيعاً نشطاً.", "المجتمع", "خزينة المشروع", "المؤسس والفريق", "المنظومة", "احتياطي السيولة", "المقترح: قفل 90% من حصص المجتمع والخزينة والمنظومة و100% من حصة الفريق، أي 87% من الإجمالي. لا تحرير لمدة 24 شهراً تقويمياً، ثم شهرياً على مدى 36 شهراً. تحتاج السيولة أيضاً إلى SOL أو USDC؛ حجز التوكنات لا يموّل السوق وحده.", "تم التحقق على Devnet من الإنشاء والبيانات الوصفية وخزنة المؤسس. المتبقي: تجربة 20 رصيد ذكاء اصطناعي / 7 أيام، والمدفوعات والأهلية وقفل السيولة الفعلي. تتطلب Mainnet تدقيقاً مستقلاً ومراجعة قانونية وإدارة موثقة. لا وعد بموعد إطلاق أو عائد.", "توزيع التوكن المقترح"]
};

export const allocationPercentages = [40, 25, 15, 15, 5];
if (typeof document !== "undefined") {
  const section = document.getElementById("jamd-roadmap");
  const render = () => {
    const locale = document.documentElement.lang.split("-")[0];
    const copy = roadmapCopy[locale] || roadmapCopy.en;
    const format = new Intl.NumberFormat(roadmapCopy[locale] ? locale : "en");
    const node = (tag, text) => { const el = document.createElement(tag); el.textContent = text; return el; };
    section.lang = roadmapCopy[locale] ? locale : "en";
    section.dir = section.lang === "ar" ? "rtl" : "ltr";
    section.replaceChildren(node("h2", copy[0]), node("p", copy[1]));
    const list = document.createElement("ul");
    list.setAttribute("aria-label", copy[9]);
    allocationPercentages.forEach((percent, index) => {
      list.append(node("li", `${copy[index + 2]}: ${new Intl.NumberFormat(section.lang, {style: "percent"}).format(percent / 100)} · ${format.format(percent * 10000000)} JAMD`));
    });
    section.append(list, node("p", copy[7]), node("p", copy[8]));
  };
  if (section) {
    render();
    new MutationObserver(render).observe(document.documentElement, { attributes: true, attributeFilter: ["lang"] });
  }
}
