import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
test('native test vault is unregistered and hardware-authenticated',()=>{
 const source=readFileSync(new URL('../android/app/src/main/java/com/jamddmaj/ai/wallet/HardwareTestVault.java',import.meta.url),'utf8');
 assert.match(source,/getNoBackupFilesDir/);
 assert.match(source,/setUserAuthenticationParameters\(0, KeyProperties.AUTH_BIOMETRIC_STRONG\)/);
 assert.match(source,/isUserAuthenticationRequirementEnforcedBySecureHardware/);
 assert.match(source,/cipher\.updateAAD\(aad\)/);
 assert.doesNotMatch(source,/JavascriptInterface|CapacitorPlugin|Log\.|System\.out|SharedPreferences/);
 const activity=readFileSync(new URL('../android/app/src/main/java/com/jamddmaj/ai/MainActivity.java',import.meta.url),'utf8');
 assert.doesNotMatch(activity,/HardwareTestVault/);
 const plugin=readFileSync(new URL('../android/app/src/main/java/com/jamddmaj/ai/DevnetWalletPlugin.java',import.meta.url),'utf8');
 assert.match(plugin,/"localhost"\.equals\(page.getHost\(\)\)/);
 assert.match(plugin,/"\/private-simulator.html"\.equals\(page.getPath\(\)\)/);
 assert.doesNotMatch(plugin,/putExtra|call.getString|HardwareTestVault|signReviewed|submit\(/);
 const manifest=readFileSync(new URL('../android/app/src/main/AndroidManifest.xml',import.meta.url),'utf8');
 assert.match(manifest,/DevnetWalletActivity"\s+android:exported="false"/);
});
test('native devnet wallet has no web bridge, mainnet endpoint or automatic submission',()=>{
 const root=new URL('../android/app/src/main/java/com/jamddmaj/ai/wallet/',import.meta.url);
 const service=readFileSync(new URL('DevnetWalletService.java',root),'utf8');
 const activity=readFileSync(new URL('DevnetWalletActivity.java',root),'utf8');
 assert.match(service,/https:\/\/api\.devnet\.solana\.com/);
 assert.match(service,/EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG/);
 assert.match(service,/draft\.consumed=true/);
 assert.ok(service.indexOf('write(journalFile,record)')<service.indexOf('rpc("sendTransaction"'));
 assert.match(service,/setInstanceFollowRedirects\(false\)/);
 assert.match(activity,/getCipher\(\)!=operation.authenticationCipher\(\)/);
 assert.match(activity,/Confirm with biometrics/);
 assert.doesNotMatch(service+activity,/api\.mainnet|JavascriptInterface|CapacitorPlugin|Log\./);
});
test('diagnostic UI authenticates exact cipher, locks on stop and is isolated from production',()=>{
 const activity=readFileSync(new URL('../android/app/src/debug/java/com/jamddmaj/ai/wallet/VaultDiagnosticActivity.java',import.meta.url),'utf8');
 assert.match(activity,/FLAG_SECURE/);
 assert.match(activity,/getCipher\(\)!=operation.authenticationCipher\(\)/);
 assert.match(activity,/onStop\(\)\{lock\(\)/);
 assert.match(activity,/onDestroy\(\)\{lock\(\)/);
 assert.doesNotMatch(activity,/WebView|loadUrl|registerPlugin|http[s]?:|Log\./);
 const manifest=readFileSync(new URL('../android/app/src/debug/AndroidManifest.xml',import.meta.url),'utf8');
 assert.match(manifest,/android:allowBackup="false"/);
 assert.match(manifest,/android:usesCleartextTraffic="false"/);
 const gradle=readFileSync(new URL('../android/app/build.gradle',import.meta.url),'utf8');
 assert.match(gradle,/applicationIdSuffix "\.walletlab\.devnet"/);
});
