[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
jamddmaj_lock = "FzH2QN9NFFrpwsn8xqLT83BZ7ruqmMBiwY4CU6MkLVQ4"

[programs.devnet]
jamddmaj_lock = "FzH2QN9NFFrpwsn8xqLT83BZ7ruqmMBiwY4CU6MkLVQ4"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
