[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
jamddmaj_lock = "BZMa3Aubxg1K3yx6oSN2nCnUcSJw6t7y55yCe7nZvx9V"

[programs.devnet]
jamddmaj_lock = "BZMa3Aubxg1K3yx6oSN2nCnUcSJw6t7y55yCe7nZvx9V"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
