export const MARKETS_CATALOG = [
        { symbol: "BTC", id: "bitcoin", binance: "BTCUSDT", category: "Payments and stores of value" },
        { symbol: "XRP", id: "ripple", binance: "XRPUSDT", category: "Payments and stores of value" },
        { symbol: "LTC", id: "litecoin", binance: "LTCUSDT", category: "Payments and stores of value" },
        { symbol: "BCH", id: "bitcoin-cash", binance: "BCHUSDT", category: "Payments and stores of value" },
        { symbol: "XLM", id: "stellar", binance: "XLMUSDT", category: "Payments and stores of value" },
        { symbol: "TRX", id: "tron", binance: "TRXUSDT", category: "Payments and stores of value" },
        { symbol: "TON", id: "toncoin", binance: "TONUSDT", category: "Payments and stores of value" },
        { symbol: "ETH", id: "ethereum", binance: "ETHUSDT", category: "Layer 1 networks" },
        { symbol: "SOL", id: "solana", binance: "SOLUSDT", category: "Layer 1 networks" },
        { symbol: "BNB", id: "binancecoin", binance: "BNBUSDT", category: "Layer 1 networks" },
        { symbol: "ADA", id: "cardano", binance: "ADAUSDT", category: "Layer 1 networks" },
        { symbol: "AVAX", id: "avalanche-2", binance: "AVAXUSDT", category: "Layer 1 networks" },
        { symbol: "DOT", id: "polkadot", binance: "DOTUSDT", category: "Layer 1 networks" },
        { symbol: "NEAR", id: "near", binance: "NEARUSDT", category: "Layer 1 networks" },
        { symbol: "SUI", id: "sui", binance: "SUIUSDT", category: "Layer 1 networks" },
        { symbol: "APT", id: "aptos", binance: "APTUSDT", category: "Layer 1 networks" },
        { symbol: "ATOM", id: "cosmos", binance: "ATOMUSDT", category: "Layer 1 networks" },
        { symbol: "HBAR", id: "hedera-hashgraph", binance: "HBARUSDT", category: "Layer 1 networks" },
        { symbol: "ICP", id: "internet-computer", binance: "ICPUSDT", category: "Layer 1 networks" },
        { symbol: "ETC", id: "ethereum-classic", binance: "ETCUSDT", category: "Layer 1 networks" },
        { symbol: "VET", id: "vechain", binance: "VETUSDT", category: "Layer 1 networks" },
        { symbol: "ALGO", id: "algorand", binance: "ALGOUSDT", category: "Layer 1 networks" },
        { symbol: "EGLD", id: "elrond-erd-2", binance: "EGLDUSDT", category: "Layer 1 networks" },
        { symbol: "KAVA", id: "kava", binance: "KAVAUSDT", category: "Layer 1 networks" },
        { symbol: "SEI", id: "sei-network", binance: "SEIUSDT", category: "Layer 1 networks" },
        { symbol: "INJ", id: "injective-protocol", binance: "INJUSDT", category: "Layer 1 networks" },
        { symbol: "TIA", id: "celestia", binance: "TIAUSDT", category: "Layer 1 networks" },
        { symbol: "JUP", id: "jupiter-exchange-solana", binance: "JUPUSDT", category: "Layer 1 networks" },
        { symbol: "PYTH", id: "pyth-network", binance: "PYTHUSDT", category: "Layer 1 networks" },
        { symbol: "STX", id: "blockstack", binance: "STXUSDT", category: "Layer 1 networks" },
        { symbol: "RUNE", id: "thorchain", binance: "RUNEUSDT", category: "Layer 1 networks" },
        { symbol: "KAS", id: "kaspa", binance: "KASUSDT", category: "Layer 1 networks" },
        { symbol: "IOTA", id: "iota", binance: "IOTAUSDT", category: "Layer 1 networks" },
        { symbol: "ROSE", id: "oasis-network", binance: "ROSEUSDT", category: "Layer 1 networks" },
        { symbol: "ZEC", id: "zcash", binance: "ZECUSDT", category: "Layer 1 networks" },
        { symbol: "DASH", id: "dash", binance: "DASHUSDT", category: "Layer 1 networks" },
        { symbol: "XMR", id: "monero", binance: "XMRUSDT", category: "Layer 1 networks" },
        { symbol: "QNT", id: "quant-network", binance: "QNTUSDT", category: "Layer 1 networks" },
        { symbol: "POL", id: "polygon-ecosystem-token", binance: "POLUSDT", category: "Layer 2 scaling" },
        { symbol: "ARB", id: "arbitrum", binance: "ARBUSDT", category: "Layer 2 scaling" },
        { symbol: "OP", id: "optimism", binance: "OPUSDT", category: "Layer 2 scaling" },
        { symbol: "IMX", id: "immutable-x", binance: "IMXUSDT", category: "Layer 2 scaling" },
        { symbol: "MNT", id: "mantle", binance: "MNTUSDT", category: "Layer 2 scaling" },
        { symbol: "STRK", id: "starknet", binance: "STRKUSDT", category: "Layer 2 scaling" },
        { symbol: "ZK", id: "zksync", binance: "ZKUSDT", category: "Layer 2 scaling" },
        { symbol: "ZRO", id: "layerzero", binance: "ZROUSDT", category: "Layer 2 scaling" },
        { symbol: "METIS", id: "metis-token", binance: "METISUSDT", category: "Layer 2 scaling" },
        { symbol: "BLAST", id: "blast", binance: "BLASTUSDT", category: "Layer 2 scaling" },
        { symbol: "OKB", id: "okb", binance: "OKBUSDT", category: "Exchange tokens" },
        { symbol: "CRO", id: "crypto-com-chain", binance: "CROUSDT", category: "Exchange tokens" },
        { symbol: "LEO", id: "leo-token", binance: "LEOUSDT", category: "Exchange tokens" },
        { symbol: "KCS", id: "kucoin-shares", binance: "KCSUSDT", category: "Exchange tokens" },
        { symbol: "GT", id: "gatechain-token", binance: "GTUSDT", category: "Exchange tokens" },
        { symbol: "BGB", id: "bitget-token", binance: "BGBUSDT", category: "Exchange tokens" },
        { symbol: "MX", id: "mx-token", binance: "MXUSDT", category: "Exchange tokens" },
        { symbol: "WOO", id: "woo-network", binance: "WOOUSDT", category: "Exchange tokens" },
        { symbol: "UNI", id: "uniswap", binance: "UNIUSDT", category: "DeFi and governance" },
        { symbol: "AAVE", id: "aave", binance: "AAVEUSDT", category: "DeFi and governance" },
        { symbol: "MKR", id: "maker", binance: "MKRUSDT", category: "DeFi and governance" },
        { symbol: "CRV", id: "curve-dao-token", binance: "CRVUSDT", category: "DeFi and governance" },
        { symbol: "LDO", id: "lido-dao", binance: "LDOUSDT", category: "DeFi and governance" },
        { symbol: "COMP", id: "compound-governance-token", binance: "COMPUSDT", category: "DeFi and governance" },
        { symbol: "CAKE", id: "pancakeswap-token", binance: "CAKEUSDT", category: "DeFi and governance" },
        { symbol: "ONDO", id: "ondo-finance", binance: "ONDOUSDT", category: "DeFi and governance" },
        { symbol: "PENDLE", id: "pendle", binance: "PENDLEUSDT", category: "DeFi and governance" },
        { symbol: "ENA", id: "ethena", binance: "ENAUSDT", category: "DeFi and governance" },
        { symbol: "JTO", id: "jito-governance-token", binance: "JTOUSDT", category: "DeFi and governance" },
        { symbol: "SNX", id: "havven", binance: "SNXUSDT", category: "DeFi and governance" },
        { symbol: "DYDX", id: "dydx-chain", binance: "DYDXUSDT", category: "DeFi and governance" },
        { symbol: "1INCH", id: "1inch", binance: "1INCHUSDT", category: "DeFi and governance" },
        { symbol: "RPL", id: "rocket-pool", binance: "RPLUSDT", category: "DeFi and governance" },
        { symbol: "FXS", id: "frax-share", binance: "FXSUSDT", category: "DeFi and governance" },
        { symbol: "GMX", id: "gmx", binance: "GMXUSDT", category: "DeFi and governance" },
        { symbol: "RAY", id: "raydium", binance: "RAYUSDT", category: "DeFi and governance" },
        { symbol: "JOE", id: "joe", binance: "JOEUSDT", category: "DeFi and governance" },
        { symbol: "JST", id: "just", binance: "JSTUSDT", category: "DeFi and governance" },
        { symbol: "SUSHI", id: "sushi", binance: "SUSHIUSDT", category: "DeFi and governance" },
        { symbol: "BAL", id: "balancer", binance: "BALUSDT", category: "DeFi and governance" },
        { symbol: "YFI", id: "yearn-finance", binance: "YFIUSDT", category: "DeFi and governance" },
        { symbol: "ZRX", id: "0x", binance: "ZRXUSDT", category: "DeFi and governance" },
        { symbol: "AEVO", id: "aevo-exchange", binance: "AEVOUSDT", category: "DeFi and governance" },
        { symbol: "LINK", id: "chainlink", binance: "LINKUSDT", category: "AI, data and infrastructure" },
        { symbol: "FET", id: "fetch-ai", binance: "FETUSDT", category: "AI, data and infrastructure" },
        { symbol: "RENDER", id: "render-token", binance: "RENDERUSDT", category: "AI, data and infrastructure" },
        { symbol: "TAO", id: "bittensor", binance: "TAOUSDT", category: "AI, data and infrastructure" },
        { symbol: "GRT", id: "the-graph", binance: "GRTUSDT", category: "AI, data and infrastructure" },
        { symbol: "FIL", id: "filecoin", binance: "FILUSDT", category: "AI, data and infrastructure" },
        { symbol: "W", id: "wormhole", binance: "WUSDT", category: "AI, data and infrastructure" },
        { symbol: "ARKM", id: "arkham", binance: "ARKMUSDT", category: "AI, data and infrastructure" },
        { symbol: "WLD", id: "worldcoin-wld", binance: "WLDUSDT", category: "AI, data and infrastructure" },
        { symbol: "JASMY", id: "jasmycoin", binance: "JASMYUSDT", category: "AI, data and infrastructure" },
        { symbol: "AIOZ", id: "aioz-network", binance: "AIOZUSDT", category: "AI, data and infrastructure" },
        { symbol: "AKT", id: "akash-network", binance: "AKTUSDT", category: "AI, data and infrastructure" },
        { symbol: "AR", id: "arweave", binance: "ARUSDT", category: "AI, data and infrastructure" },
        { symbol: "FTM", id: "fantom", binance: "FTMUSDT", category: "AI, data and infrastructure" },
        { symbol: "HYPE", id: "hyperliquid", binance: "HYPEUSDT", category: "AI, data and infrastructure" },
        { symbol: "PENGU", id: "pudgy-penguins", binance: "PENGUUSDT", category: "AI, data and infrastructure" },
        { symbol: "IO", id: "io", binance: "IOUSDT", category: "AI, data and infrastructure" },
        { symbol: "GRASS", id: "grass", binance: "GRASSUSDT", category: "AI, data and infrastructure" },
        { symbol: "VIRTUAL", id: "virtual-protocol", binance: "VIRTUALUSDT", category: "AI, data and infrastructure" },
        { symbol: "COOKIE", id: "cookie", binance: "COOKIEUSDT", category: "AI, data and infrastructure" },
        { symbol: "PHA", id: "pha", binance: "PHAUSDT", category: "AI, data and infrastructure" },
        { symbol: "OCEAN", id: "ocean-protocol", binance: "OCEANUSDT", category: "AI, data and infrastructure" },
        { symbol: "NMR", id: "numeraire", binance: "NMRUSDT", category: "AI, data and infrastructure" },
        { symbol: "SAND", id: "the-sandbox", binance: "SANDUSDT", category: "Gaming and culture" },
        { symbol: "MANA", id: "decentraland", binance: "MANAUSDT", category: "Gaming and culture" },
        { symbol: "GALA", id: "gala", binance: "GALAUSDT", category: "Gaming and culture" },
        { symbol: "AXS", id: "axie-infinity", binance: "AXSUSDT", category: "Gaming and culture" },
        { symbol: "APE", id: "apecoin", binance: "APEUSDT", category: "Gaming and culture" },
        { symbol: "CHZ", id: "chiliz", binance: "CHZUSDT", category: "Gaming and culture" },
        { symbol: "ENJ", id: "enjincoin", binance: "ENJUSDT", category: "Gaming and culture" },
        { symbol: "ILV", id: "illuvium", binance: "ILVUSDT", category: "Gaming and culture" },
        { symbol: "PIXEL", id: "pixels", binance: "PIXELUSDT", category: "Gaming and culture" },
        { symbol: "PORTAL", id: "portal-2", binance: "PORTALUSDT", category: "Gaming and culture" },
        { symbol: "GMT", id: "stepn", binance: "GMTUSDT", category: "Gaming and culture" },
        { symbol: "YGG", id: "yield-guild-games", binance: "YGGUSDT", category: "Gaming and culture" },
        { symbol: "BEAM", id: "beam-2", binance: "BEAMUSDT", category: "Gaming and culture" },
        { symbol: "DOGE", id: "dogecoin", binance: "DOGEUSDT", category: "Community and meme coins" },
        { symbol: "SHIB", id: "shiba-inu", binance: "SHIBUSDT", category: "Community and meme coins" },
        { symbol: "PEPE", id: "pepe", binance: "PEPEUSDT", category: "Community and meme coins" },
        { symbol: "BONK", id: "bonk", binance: "BONKUSDT", category: "Community and meme coins" },
        { symbol: "WIF", id: "dogwifcoin", binance: "WIFUSDT", category: "Community and meme coins" },
        { symbol: "FLOKI", id: "floki", binance: "FLOKIUSDT", category: "Community and meme coins" },
        { symbol: "TURBO", id: "turbo", binance: "TURBOUSDT", category: "Community and meme coins" },
        { symbol: "MEME", id: "memecoin-2", binance: "MEMEUSDT", category: "Community and meme coins" },
        { symbol: "BRETT", id: "based-brett", binance: "BRETTUSDT", category: "Community and meme coins" },
        { symbol: "POPCAT", id: "popcat", binance: "POPCATUSDT", category: "Community and meme coins" },
        { symbol: "MEW", id: "cat-in-a-dogs-world", binance: "MEWUSDT", category: "Community and meme coins" },
        { symbol: "PNUT", id: "peanut-the-squirrel", binance: "PNUTUSDT", category: "Community and meme coins" },
        { symbol: "MOG", id: "mog-coin", binance: "MOGUSDT", category: "Community and meme coins" },
        { symbol: "TRUMP", id: "official-trump", binance: "TRUMPUSDT", category: "Community and meme coins" },
        { symbol: "FARTCOIN", id: "fartcoin", binance: "FARTCOINUSDT", category: "Community and meme coins" },
        { symbol: "BOME", id: "book-of-meme", binance: "BOMEUSDT", category: "Community and meme coins" },
        { symbol: "NOT", id: "notcoin", binance: "NOTUSDT", category: "Community and meme coins" },
        { symbol: "DOGS", id: "dogs-2", binance: "DOGSUSDT", category: "Community and meme coins" },
        { symbol: "NEIRO", id: "neiro-3", binance: "NEIROUSDT", category: "Community and meme coins" },
        { symbol: "ACT", id: "act-i-the-ai-prophecy", binance: "ACTUSDT", category: "Community and meme coins" },
        { symbol: "GOAT", id: "goatseus-maximus", binance: "GOATUSDT", category: "Community and meme coins" },
        { symbol: "FWOG", id: "fwog", binance: "FWOGUSDT", category: "Community and meme coins" }
      ];

